"""Add BookDemo model with status

Revision ID: 1e3047189639
Revises: 36d57ef7bc5c
Create Date: 2025-10-12 21:06:54.274916

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1e3047189639'
down_revision: Union[str, None] = '36d57ef7bc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_demo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_demo_email'), 'book_demo', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_demo_email'), table_name='book_demo')
    op.drop_table('book_demo')
    # ### end Alembic commands ###
