"""Add is_admin column to user table

Revision ID: 36d57ef7bc5c
Revises: b83acd7629ec
Create Date: 2025-10-06 01:16:05.277638

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36d57ef7bc5c'
down_revision: Union[str, None] = 'b83acd7629ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add column as nullable
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))

    # Step 2: Set default value for existing users
    op.execute("UPDATE \"user\" SET is_admin = false WHERE is_admin IS NULL")

    # Step 3: Make column not nullable
    op.alter_column('user', 'is_admin', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
