// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { RootHealthGetResponse } from './types.gen';

export class DefaultService {
    /**
     * Root
     * Root endpoint - API health check
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static rootHealthGet(): CancelablePromise<RootHealthGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health'
        });
    }
    
}