// This file is auto-generated by @hey-api/openapi-ts

/**
 * Authentication response with token and user data.
 */
export type Auth = {
    access_token: string;
    user: UserPublic;
};

export type ChangePasswordRequest = {
    old_password: string;
    new_password: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ForgotPasswordVerifyRequest = {
    token: string;
    user_id: string;
    new_password: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * Simple message response.
 */
export type Message = {
    message: string;
};

export type SignupRequest = {
    email: string;
    password: string;
    full_name: string;
};

export type TwoFactorAuthVerifyRequest = {
    totp: string;
};

export type UpdateUserRequest = {
    full_name?: (string | null);
};

export type URL = {
    url: string;
};

/**
 * Public user model for API responses.
 */
export type UserPublic = {
    id: string;
    email: string;
    full_name: string;
    signup_verified: (string | null);
    auth_provider: string;
    avatar_url: (string | null);
    is_admin: boolean;
    two_fa_enabled: boolean;
    pending_2fa?: boolean;
    created_at: string;
    updated_at: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VerifySignupRequest = {
    signup_token: string;
};

export type ServeVideoVideoFilePathGetData = {
    filePath: string;
};

export type ServeVideoVideoFilePathGetResponse = (unknown);

export type ServeImagesImagesFilePathGetData = {
    filePath: string;
};

export type ServeImagesImagesFilePathGetResponse = (unknown);

export type ServeFrontendPathGetData = {
    path: string;
};

export type ServeFrontendPathGetResponse = (unknown);

export type RequestApiV1ForgotPasswordPostData = {
    requestBody: ForgotPasswordRequest;
};

export type RequestApiV1ForgotPasswordPostResponse = (Message);

export type VerifyApiV1ForgotPasswordVerifyPostData = {
    requestBody: ForgotPasswordVerifyRequest;
};

export type VerifyApiV1ForgotPasswordVerifyPostResponse = (Message);

export type CheckApiV1HealthGetResponse = (unknown);

export type SetupApiV1TwoFaSetupGetResponse = (URL);

export type VerifyApiV1TwoFaVerifyPostData = {
    requestBody: TwoFactorAuthVerifyRequest;
};

export type VerifyApiV1TwoFaVerifyPostResponse = (unknown);

export type VerifyCodeApiV1TwoFaVerifyCodePostData = {
    requestBody: TwoFactorAuthVerifyRequest;
};

export type VerifyCodeApiV1TwoFaVerifyCodePostResponse = (Auth);

export type DisableApiV1TwoFaDisablePostResponse = (unknown);

export type SignupApiV1UserSignupPostData = {
    requestBody: SignupRequest;
};

export type SignupApiV1UserSignupPostResponse = (Auth);

export type ResendVerificationApiV1UserResendVerificationPostResponse = (Message);

export type VerifySignupApiV1UserVerifySignupPostData = {
    requestBody: VerifySignupRequest;
};

export type VerifySignupApiV1UserVerifySignupPostResponse = (UserPublic);

export type LoginApiV1UserLoginPostData = {
    requestBody: LoginRequest;
};

export type LoginApiV1UserLoginPostResponse = (Auth);

export type GetMeApiV1UserMeGetResponse = (UserPublic);

export type UpdateApiV1UserPutData = {
    requestBody: UpdateUserRequest;
};

export type UpdateApiV1UserPutResponse = (UserPublic);

export type DeleteApiV1UserDeleteResponse = (Message);

export type ChangePasswordApiV1UserChangePasswordPostData = {
    requestBody: ChangePasswordRequest;
};

export type ChangePasswordApiV1UserChangePasswordPostResponse = (Message);