// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RootHealthGetResponse = (unknown);

export type ServeFrontendPathGetData = {
    path: string;
};

export type ServeFrontendPathGetResponse = (unknown);